# Generated by Django 5.0 on 2023-12-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=194, unique=True, verbose_name='Email do Usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário está Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário e um Dev')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Usuario é um Superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': ('Usuário',),
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
    ]
