# Generated by Django 5.0 on 2023-12-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF do visitante')),
                ('autorizado', models.BooleanField(default=False, verbose_name='O visitante está autorizado ')),
            ],
        ),
    ]
