# Generated by Django 5.0 on 2023-12-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_alter_visitantes_options_remove_visitantes_sobrenome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='horario_chegada',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Horário de chegada na portaria'),
        ),
    ]
