# Generated by Django 4.2.8 on 2023-12-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
        ('visitantes', '0004_alter_visitantes_autorizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='registrado_por',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='porteiros.porteiro', verbose_name='Porteiro responsável pelo registro'),
            preserve_default=False,
        ),
    ]
